image: ubuntu:latest

variables:
  EXPORT_NAME: foveal
  GODOT_BUILD: Godot_v4.4-beta2_mono_linux_x86_64
  GODOT_DOWNLOAD_URL: https://github.com/godotengine/godot-builds/releases/download/4.4-beta2/Godot_v4.4-beta2_mono_linux_x86_64.zip

stages:
  - setup
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .wine
    - .config/godot
    - .local/share/godot
    - .cache/godot
  policy: pull-push

setup-environment:
  stage: setup
  script:
    - apt-get update -qq
    - apt-get install -y wget unzip wine64
    - wget -O godot.zip ${GODOT_DOWNLOAD_URL}
    - unzip godot.zip
    - chmod +x ${GODOT_BUILD}/${GODOT_BUILD}
    - ${GODOT_BUILD}/${GODOT_BUILD} --version
  artifacts:
    paths:
      - ${GODOT_BUILD}
    expire_in: 1 week

windows:
  stage: build
  needs: [setup-environment]
  script:
    - ${GODOT_BUILD}/${GODOT_BUILD} --headless --export-templates
    - ${GODOT_BUILD}/${GODOT_BUILD} --headless --export-release "Windows Desktop" "build/${EXPORT_NAME}.exe"
  artifacts:
    paths:
      - build/${EXPORT_NAME}.exe
    expire_in: 1 week
